// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package taxPaymentService;

public interface ListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:paymentServices.ListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ask = 1;</code>
   */
  java.lang.String getAsk();
  /**
   * <code>string ask = 1;</code>
   */
  com.google.protobuf.ByteString
      getAskBytes();
}
