// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package taxPaymentService;

public interface ListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:paymentServices.ListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ans = 1;</code>
   */
  java.lang.String getAns();
  /**
   * <code>string ans = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnsBytes();
}
