// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package taxPaymentService;

public final class PaymentBalanceServiceImpl {
  private PaymentBalanceServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentServices_PaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paymentServices_PaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentServices_PaymentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paymentServices_PaymentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentServices_TaxPaymentsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paymentServices_TaxPaymentsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentServices_TaxPaymentsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paymentServices_TaxPaymentsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentServices_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paymentServices_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentServices_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paymentServices_ListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpayment.proto\022\017paymentServices\"\"\n\016Paym" +
      "entRequest\022\020\n\010totalDue\030\001 \001(\t\"#\n\017PaymentR" +
      "esponse\022\020\n\010totalDue\030\001 \001(\t\")\n\022TaxPayments" +
      "Request\022\023\n\013taxPayments\030\001 \001(\t\"*\n\023TaxPayme" +
      "ntsResponse\022\023\n\013taxPayments\030\001 \001(\t\"\032\n\013List" +
      "Request\022\013\n\003ask\030\001 \001(\t\"\033\n\014ListResponse\022\013\n\003" +
      "ans\030\001 \001(\t2\234\002\n\016AmountTotalDue\022P\n\013checkAmo" +
      "unt\022\037.paymentServices.PaymentRequest\032 .p" +
      "aymentServices.PaymentResponse\022S\n\020Listov" +
      "erduepayer\022\034.paymentServices.ListRequest" +
      "\032\035.paymentServices.ListResponse\"\0000\001\022c\n\022c" +
      "onfirmTaxPayments\022#.paymentServices.TaxP" +
      "aymentsRequest\032$.paymentServices.TaxPaym" +
      "entsResponse(\0010\001B0\n\021taxPaymentServiceB\031P" +
      "aymentBalanceServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_paymentServices_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_paymentServices_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paymentServices_PaymentRequest_descriptor,
        new java.lang.String[] { "TotalDue", });
    internal_static_paymentServices_PaymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_paymentServices_PaymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paymentServices_PaymentResponse_descriptor,
        new java.lang.String[] { "TotalDue", });
    internal_static_paymentServices_TaxPaymentsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_paymentServices_TaxPaymentsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paymentServices_TaxPaymentsRequest_descriptor,
        new java.lang.String[] { "TaxPayments", });
    internal_static_paymentServices_TaxPaymentsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_paymentServices_TaxPaymentsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paymentServices_TaxPaymentsResponse_descriptor,
        new java.lang.String[] { "TaxPayments", });
    internal_static_paymentServices_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_paymentServices_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paymentServices_ListRequest_descriptor,
        new java.lang.String[] { "Ask", });
    internal_static_paymentServices_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_paymentServices_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paymentServices_ListResponse_descriptor,
        new java.lang.String[] { "Ans", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
