// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package taxPaymentService;

public interface PaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:paymentServices.PaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string totalDue = 1;</code>
   */
  java.lang.String getTotalDue();
  /**
   * <code>string totalDue = 1;</code>
   */
  com.google.protobuf.ByteString
      getTotalDueBytes();
}
