// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package taxPaymentService;

public interface TaxPaymentsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:paymentServices.TaxPaymentsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string taxPayments = 1;</code>
   */
  java.lang.String getTaxPayments();
  /**
   * <code>string taxPayments = 1;</code>
   */
  com.google.protobuf.ByteString
      getTaxPaymentsBytes();
}
