// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customerAdmin.proto

package customerAdminService;

public interface CalculateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CustomerAdminService.CalculateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string customerName = 1;</code>
   */
  java.lang.String getCustomerName();
  /**
   * <code>string customerName = 1;</code>
   */
  com.google.protobuf.ByteString
      getCustomerNameBytes();

  /**
   * <code>int32 numberVehicle = 2;</code>
   */
  int getNumberVehicle();

  /**
   * <code>.CustomerAdminService.CalculateRequest.VehicleType vehicleType = 3;</code>
   */
  int getVehicleTypeValue();
  /**
   * <code>.CustomerAdminService.CalculateRequest.VehicleType vehicleType = 3;</code>
   */
  customerAdminService.CalculateRequest.VehicleType getVehicleType();
}
