// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customerAdmin.proto

package customerAdminService;

/**
 * <pre>
 *&#47;//Unary Call
 * </pre>
 *
 * Protobuf type {@code CustomerAdminService.CalculateRequest}
 */
public  final class CalculateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CustomerAdminService.CalculateRequest)
    CalculateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CalculateRequest.newBuilder() to construct.
  private CalculateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CalculateRequest() {
    customerName_ = "";
    numberVehicle_ = 0;
    vehicleType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CalculateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            customerName_ = s;
            break;
          }
          case 16: {

            numberVehicle_ = input.readInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            vehicleType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return customerAdminService.customerAdminServiceImpl.internal_static_CustomerAdminService_CalculateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return customerAdminService.customerAdminServiceImpl.internal_static_CustomerAdminService_CalculateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            customerAdminService.CalculateRequest.class, customerAdminService.CalculateRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code CustomerAdminService.CalculateRequest.VehicleType}
   */
  public enum VehicleType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DIESEL = 0;</code>
     */
    DIESEL(0),
    /**
     * <code>ELECTRIC = 1;</code>
     */
    ELECTRIC(1),
    /**
     * <code>PETROL = 2;</code>
     */
    PETROL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DIESEL = 0;</code>
     */
    public static final int DIESEL_VALUE = 0;
    /**
     * <code>ELECTRIC = 1;</code>
     */
    public static final int ELECTRIC_VALUE = 1;
    /**
     * <code>PETROL = 2;</code>
     */
    public static final int PETROL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static VehicleType valueOf(int value) {
      return forNumber(value);
    }

    public static VehicleType forNumber(int value) {
      switch (value) {
        case 0: return DIESEL;
        case 1: return ELECTRIC;
        case 2: return PETROL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<VehicleType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        VehicleType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<VehicleType>() {
            public VehicleType findValueByNumber(int number) {
              return VehicleType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return customerAdminService.CalculateRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final VehicleType[] VALUES = values();

    public static VehicleType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private VehicleType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CustomerAdminService.CalculateRequest.VehicleType)
  }

  public static final int CUSTOMERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object customerName_;
  /**
   * <code>string customerName = 1;</code>
   */
  public java.lang.String getCustomerName() {
    java.lang.Object ref = customerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      customerName_ = s;
      return s;
    }
  }
  /**
   * <code>string customerName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCustomerNameBytes() {
    java.lang.Object ref = customerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMBERVEHICLE_FIELD_NUMBER = 2;
  private int numberVehicle_;
  /**
   * <code>int32 numberVehicle = 2;</code>
   */
  public int getNumberVehicle() {
    return numberVehicle_;
  }

  public static final int VEHICLETYPE_FIELD_NUMBER = 3;
  private int vehicleType_;
  /**
   * <code>.CustomerAdminService.CalculateRequest.VehicleType vehicleType = 3;</code>
   */
  public int getVehicleTypeValue() {
    return vehicleType_;
  }
  /**
   * <code>.CustomerAdminService.CalculateRequest.VehicleType vehicleType = 3;</code>
   */
  public customerAdminService.CalculateRequest.VehicleType getVehicleType() {
    @SuppressWarnings("deprecation")
    customerAdminService.CalculateRequest.VehicleType result = customerAdminService.CalculateRequest.VehicleType.valueOf(vehicleType_);
    return result == null ? customerAdminService.CalculateRequest.VehicleType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCustomerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, customerName_);
    }
    if (numberVehicle_ != 0) {
      output.writeInt32(2, numberVehicle_);
    }
    if (vehicleType_ != customerAdminService.CalculateRequest.VehicleType.DIESEL.getNumber()) {
      output.writeEnum(3, vehicleType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCustomerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, customerName_);
    }
    if (numberVehicle_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, numberVehicle_);
    }
    if (vehicleType_ != customerAdminService.CalculateRequest.VehicleType.DIESEL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, vehicleType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof customerAdminService.CalculateRequest)) {
      return super.equals(obj);
    }
    customerAdminService.CalculateRequest other = (customerAdminService.CalculateRequest) obj;

    boolean result = true;
    result = result && getCustomerName()
        .equals(other.getCustomerName());
    result = result && (getNumberVehicle()
        == other.getNumberVehicle());
    result = result && vehicleType_ == other.vehicleType_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CUSTOMERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCustomerName().hashCode();
    hash = (37 * hash) + NUMBERVEHICLE_FIELD_NUMBER;
    hash = (53 * hash) + getNumberVehicle();
    hash = (37 * hash) + VEHICLETYPE_FIELD_NUMBER;
    hash = (53 * hash) + vehicleType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static customerAdminService.CalculateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static customerAdminService.CalculateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static customerAdminService.CalculateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static customerAdminService.CalculateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static customerAdminService.CalculateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static customerAdminService.CalculateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static customerAdminService.CalculateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static customerAdminService.CalculateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static customerAdminService.CalculateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static customerAdminService.CalculateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static customerAdminService.CalculateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static customerAdminService.CalculateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(customerAdminService.CalculateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *&#47;//Unary Call
   * </pre>
   *
   * Protobuf type {@code CustomerAdminService.CalculateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CustomerAdminService.CalculateRequest)
      customerAdminService.CalculateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return customerAdminService.customerAdminServiceImpl.internal_static_CustomerAdminService_CalculateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return customerAdminService.customerAdminServiceImpl.internal_static_CustomerAdminService_CalculateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              customerAdminService.CalculateRequest.class, customerAdminService.CalculateRequest.Builder.class);
    }

    // Construct using customerAdminService.CalculateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      customerName_ = "";

      numberVehicle_ = 0;

      vehicleType_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return customerAdminService.customerAdminServiceImpl.internal_static_CustomerAdminService_CalculateRequest_descriptor;
    }

    @java.lang.Override
    public customerAdminService.CalculateRequest getDefaultInstanceForType() {
      return customerAdminService.CalculateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public customerAdminService.CalculateRequest build() {
      customerAdminService.CalculateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public customerAdminService.CalculateRequest buildPartial() {
      customerAdminService.CalculateRequest result = new customerAdminService.CalculateRequest(this);
      result.customerName_ = customerName_;
      result.numberVehicle_ = numberVehicle_;
      result.vehicleType_ = vehicleType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof customerAdminService.CalculateRequest) {
        return mergeFrom((customerAdminService.CalculateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(customerAdminService.CalculateRequest other) {
      if (other == customerAdminService.CalculateRequest.getDefaultInstance()) return this;
      if (!other.getCustomerName().isEmpty()) {
        customerName_ = other.customerName_;
        onChanged();
      }
      if (other.getNumberVehicle() != 0) {
        setNumberVehicle(other.getNumberVehicle());
      }
      if (other.vehicleType_ != 0) {
        setVehicleTypeValue(other.getVehicleTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      customerAdminService.CalculateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (customerAdminService.CalculateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object customerName_ = "";
    /**
     * <code>string customerName = 1;</code>
     */
    public java.lang.String getCustomerName() {
      java.lang.Object ref = customerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string customerName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCustomerNameBytes() {
      java.lang.Object ref = customerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string customerName = 1;</code>
     */
    public Builder setCustomerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      customerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string customerName = 1;</code>
     */
    public Builder clearCustomerName() {
      
      customerName_ = getDefaultInstance().getCustomerName();
      onChanged();
      return this;
    }
    /**
     * <code>string customerName = 1;</code>
     */
    public Builder setCustomerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      customerName_ = value;
      onChanged();
      return this;
    }

    private int numberVehicle_ ;
    /**
     * <code>int32 numberVehicle = 2;</code>
     */
    public int getNumberVehicle() {
      return numberVehicle_;
    }
    /**
     * <code>int32 numberVehicle = 2;</code>
     */
    public Builder setNumberVehicle(int value) {
      
      numberVehicle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numberVehicle = 2;</code>
     */
    public Builder clearNumberVehicle() {
      
      numberVehicle_ = 0;
      onChanged();
      return this;
    }

    private int vehicleType_ = 0;
    /**
     * <code>.CustomerAdminService.CalculateRequest.VehicleType vehicleType = 3;</code>
     */
    public int getVehicleTypeValue() {
      return vehicleType_;
    }
    /**
     * <code>.CustomerAdminService.CalculateRequest.VehicleType vehicleType = 3;</code>
     */
    public Builder setVehicleTypeValue(int value) {
      vehicleType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.CustomerAdminService.CalculateRequest.VehicleType vehicleType = 3;</code>
     */
    public customerAdminService.CalculateRequest.VehicleType getVehicleType() {
      @SuppressWarnings("deprecation")
      customerAdminService.CalculateRequest.VehicleType result = customerAdminService.CalculateRequest.VehicleType.valueOf(vehicleType_);
      return result == null ? customerAdminService.CalculateRequest.VehicleType.UNRECOGNIZED : result;
    }
    /**
     * <code>.CustomerAdminService.CalculateRequest.VehicleType vehicleType = 3;</code>
     */
    public Builder setVehicleType(customerAdminService.CalculateRequest.VehicleType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      vehicleType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.CustomerAdminService.CalculateRequest.VehicleType vehicleType = 3;</code>
     */
    public Builder clearVehicleType() {
      
      vehicleType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CustomerAdminService.CalculateRequest)
  }

  // @@protoc_insertion_point(class_scope:CustomerAdminService.CalculateRequest)
  private static final customerAdminService.CalculateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new customerAdminService.CalculateRequest();
  }

  public static customerAdminService.CalculateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CalculateRequest>
      PARSER = new com.google.protobuf.AbstractParser<CalculateRequest>() {
    @java.lang.Override
    public CalculateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CalculateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CalculateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CalculateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public customerAdminService.CalculateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

