// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customerAdmin.proto

package customerAdminService;

public final class customerAdminServiceImpl {
  private customerAdminServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerAdminService_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerAdminService_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerAdminService_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerAdminService_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerAdminService_DisplayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerAdminService_DisplayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerAdminService_DisplayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerAdminService_DisplayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerAdminService_CalculateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerAdminService_CalculateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerAdminService_CalculateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerAdminService_CalculateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023customerAdmin.proto\022\024CustomerAdminServ" +
      "ice\"C\n\017RegisterRequest\022\014\n\004name\030\001 \001(\t\022\r\n\005" +
      "taxNo\030\002 \001(\t\022\023\n\013paymentType\030\003 \001(\t\"\"\n\020Regi" +
      "sterResponse\022\016\n\006result\030\001 \001(\t\"&\n\016DisplayR" +
      "equest\022\024\n\014customerList\030\001 \001(\t\"\'\n\017DisplayR" +
      "esponse\022\024\n\014allCustomers\030\001 \001(\t\"\275\001\n\020Calcul" +
      "ateRequest\022\024\n\014customerName\030\001 \001(\t\022\025\n\rnumb" +
      "erVehicle\030\002 \001(\005\022G\n\013vehicleType\030\003 \001(\01622.C" +
      "ustomerAdminService.CalculateRequest.Veh" +
      "icleType\"3\n\013VehicleType\022\n\n\006DIESEL\020\000\022\014\n\010E" +
      "LECTRIC\020\001\022\n\n\006PETROL\020\002\"$\n\021CalculateRespon" +
      "se\022\017\n\007message\030\002 \001(\t2\310\002\n\024CustomerAdminSer" +
      "vice\022f\n\021registerCustomers\022%.CustomerAdmi" +
      "nService.RegisterRequest\032&.CustomerAdmin" +
      "Service.RegisterResponse\"\000(\001\022c\n\020displayC" +
      "ustomers\022$.CustomerAdminService.DisplayR" +
      "equest\032%.CustomerAdminService.DisplayRes" +
      "ponse\"\0000\001\022c\n\016calculatePrice\022&.CustomerAd" +
      "minService.CalculateRequest\032\'.CustomerAd" +
      "minService.CalculateResponse\"\000B2\n\024custom" +
      "erAdminServiceB\030customerAdminServiceImpl" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CustomerAdminService_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CustomerAdminService_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerAdminService_RegisterRequest_descriptor,
        new java.lang.String[] { "Name", "TaxNo", "PaymentType", });
    internal_static_CustomerAdminService_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CustomerAdminService_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerAdminService_RegisterResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_CustomerAdminService_DisplayRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CustomerAdminService_DisplayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerAdminService_DisplayRequest_descriptor,
        new java.lang.String[] { "CustomerList", });
    internal_static_CustomerAdminService_DisplayResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CustomerAdminService_DisplayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerAdminService_DisplayResponse_descriptor,
        new java.lang.String[] { "AllCustomers", });
    internal_static_CustomerAdminService_CalculateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CustomerAdminService_CalculateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerAdminService_CalculateRequest_descriptor,
        new java.lang.String[] { "CustomerName", "NumberVehicle", "VehicleType", });
    internal_static_CustomerAdminService_CalculateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CustomerAdminService_CalculateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerAdminService_CalculateResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
