// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customerAdmin.proto

package customerAdminService;

public final class customerAdminServiceImpl {
  private customerAdminServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerAdminService_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerAdminService_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerAdminService_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerAdminService_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerAdminService_DisplayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerAdminService_DisplayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerAdminService_DisplayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerAdminService_DisplayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerAdminService_CalculateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerAdminService_CalculateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerAdminService_CalculateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerAdminService_CalculateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023customerAdmin.proto\022\024CustomerAdminServ" +
      "ice\"<\n\017RegisterRequest\022\014\n\004name\030\001 \001(\t\022\013\n\003" +
      "age\030\002 \001(\t\022\016\n\006gender\030\003 \001(\t\"\"\n\020RegisterRes" +
      "ponse\022\016\n\006result\030\001 \001(\t\"&\n\016DisplayRequest\022" +
      "\024\n\014customerList\030\001 \001(\t\"\'\n\017DisplayResponse" +
      "\022\024\n\014allCustomers\030\001 \001(\t\"\275\001\n\020CalculateRequ" +
      "est\022\024\n\014customerName\030\001 \001(\t\022\025\n\rnumberVehic" +
      "le\030\002 \001(\005\022G\n\013vehicleType\030\003 \001(\01622.Customer" +
      "AdminService.CalculateRequest.VehicleTyp" +
      "e\"3\n\013VehicleType\022\n\n\006DIESEL\020\000\022\014\n\010ELECTRIC" +
      "\020\001\022\n\n\006PETROL\020\002\"$\n\021CalculateResponse\022\017\n\007m" +
      "essage\030\002 \001(\t2\310\002\n\024CustomerAdminService\022f\n" +
      "\021registerCustomers\022%.CustomerAdminServic" +
      "e.RegisterRequest\032&.CustomerAdminService" +
      ".RegisterResponse\"\000(\001\022c\n\020displayCustomer" +
      "s\022$.CustomerAdminService.DisplayRequest\032" +
      "%.CustomerAdminService.DisplayResponse\"\000" +
      "0\001\022c\n\016calculatePrice\022&.CustomerAdminServ" +
      "ice.CalculateRequest\032\'.CustomerAdminServ" +
      "ice.CalculateResponse\"\000B2\n\024customerAdmin" +
      "ServiceB\030customerAdminServiceImplP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CustomerAdminService_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CustomerAdminService_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerAdminService_RegisterRequest_descriptor,
        new java.lang.String[] { "Name", "Age", "Gender", });
    internal_static_CustomerAdminService_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CustomerAdminService_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerAdminService_RegisterResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_CustomerAdminService_DisplayRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CustomerAdminService_DisplayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerAdminService_DisplayRequest_descriptor,
        new java.lang.String[] { "CustomerList", });
    internal_static_CustomerAdminService_DisplayResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CustomerAdminService_DisplayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerAdminService_DisplayResponse_descriptor,
        new java.lang.String[] { "AllCustomers", });
    internal_static_CustomerAdminService_CalculateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CustomerAdminService_CalculateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerAdminService_CalculateRequest_descriptor,
        new java.lang.String[] { "CustomerName", "NumberVehicle", "VehicleType", });
    internal_static_CustomerAdminService_CalculateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CustomerAdminService_CalculateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerAdminService_CalculateResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
