// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customerAdmin.proto

package customerAdminService;

public interface DisplayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CustomerAdminService.DisplayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string customerList = 1;</code>
   */
  java.lang.String getCustomerList();
  /**
   * <code>string customerList = 1;</code>
   */
  com.google.protobuf.ByteString
      getCustomerListBytes();
}
