// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customerAdmin.proto

package customerAdminService;

public interface DisplayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CustomerAdminService.DisplayResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string allCustomers = 1;</code>
   */
  java.lang.String getAllCustomers();
  /**
   * <code>string allCustomers = 1;</code>
   */
  com.google.protobuf.ByteString
      getAllCustomersBytes();
}
