// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customerAdmin.proto

package customerAdminService;

public interface RegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CustomerAdminService.RegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string taxNo = 2;</code>
   */
  java.lang.String getTaxNo();
  /**
   * <code>string taxNo = 2;</code>
   */
  com.google.protobuf.ByteString
      getTaxNoBytes();

  /**
   * <code>string paymentType = 3;</code>
   */
  java.lang.String getPaymentType();
  /**
   * <code>string paymentType = 3;</code>
   */
  com.google.protobuf.ByteString
      getPaymentTypeBytes();
}
