# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x0fpaymentServices\"\x1e\n\x0ePaymentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\" \n\x0fPaymentResponse\x12\r\n\x05value\x18\x01 \x01(\t\")\n\x12TaxPaymentsRequest\x12\x13\n\x0btaxPayments\x18\x01 \x01(\t\"*\n\x13TaxPaymentsResponse\x12\x13\n\x0btaxPayments\x18\x01 \x01(\t\"\x1a\n\x0bListRequest\x12\x0b\n\x03\x61sk\x18\x01 \x01(\t\"\x1b\n\x0cListResponse\x12\x0b\n\x03\x61ns\x18\x01 \x01(\t2\x9c\x02\n\x0e\x41mountTotalDue\x12P\n\x0b\x63heckAmount\x12\x1f.paymentServices.PaymentRequest\x1a .paymentServices.PaymentResponse\x12S\n\x10Listoverduepayer\x12\x1c.paymentServices.ListRequest\x1a\x1d.paymentServices.ListResponse\"\x00\x30\x01\x12\x63\n\x12\x63onfirmTaxPayments\x12#.paymentServices.TaxPaymentsRequest\x1a$.paymentServices.TaxPaymentsResponse(\x01\x30\x01\x42\x34\n\x11taxPaymentServiceB\x18\x41mountBalanceServiceImplP\x01\xa2\x02\x02SGb\x06proto3')



_PAYMENTREQUEST = DESCRIPTOR.message_types_by_name['PaymentRequest']
_PAYMENTRESPONSE = DESCRIPTOR.message_types_by_name['PaymentResponse']
_TAXPAYMENTSREQUEST = DESCRIPTOR.message_types_by_name['TaxPaymentsRequest']
_TAXPAYMENTSRESPONSE = DESCRIPTOR.message_types_by_name['TaxPaymentsResponse']
_LISTREQUEST = DESCRIPTOR.message_types_by_name['ListRequest']
_LISTRESPONSE = DESCRIPTOR.message_types_by_name['ListResponse']
PaymentRequest = _reflection.GeneratedProtocolMessageType('PaymentRequest', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTREQUEST,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:paymentServices.PaymentRequest)
  })
_sym_db.RegisterMessage(PaymentRequest)

PaymentResponse = _reflection.GeneratedProtocolMessageType('PaymentResponse', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTRESPONSE,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:paymentServices.PaymentResponse)
  })
_sym_db.RegisterMessage(PaymentResponse)

TaxPaymentsRequest = _reflection.GeneratedProtocolMessageType('TaxPaymentsRequest', (_message.Message,), {
  'DESCRIPTOR' : _TAXPAYMENTSREQUEST,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:paymentServices.TaxPaymentsRequest)
  })
_sym_db.RegisterMessage(TaxPaymentsRequest)

TaxPaymentsResponse = _reflection.GeneratedProtocolMessageType('TaxPaymentsResponse', (_message.Message,), {
  'DESCRIPTOR' : _TAXPAYMENTSRESPONSE,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:paymentServices.TaxPaymentsResponse)
  })
_sym_db.RegisterMessage(TaxPaymentsResponse)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQUEST,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:paymentServices.ListRequest)
  })
_sym_db.RegisterMessage(ListRequest)

ListResponse = _reflection.GeneratedProtocolMessageType('ListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTRESPONSE,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:paymentServices.ListResponse)
  })
_sym_db.RegisterMessage(ListResponse)

_AMOUNTTOTALDUE = DESCRIPTOR.services_by_name['AmountTotalDue']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021taxPaymentServiceB\030AmountBalanceServiceImplP\001\242\002\002SG'
  _PAYMENTREQUEST._serialized_start=34
  _PAYMENTREQUEST._serialized_end=64
  _PAYMENTRESPONSE._serialized_start=66
  _PAYMENTRESPONSE._serialized_end=98
  _TAXPAYMENTSREQUEST._serialized_start=100
  _TAXPAYMENTSREQUEST._serialized_end=141
  _TAXPAYMENTSRESPONSE._serialized_start=143
  _TAXPAYMENTSRESPONSE._serialized_end=185
  _LISTREQUEST._serialized_start=187
  _LISTREQUEST._serialized_end=213
  _LISTRESPONSE._serialized_start=215
  _LISTRESPONSE._serialized_end=242
  _AMOUNTTOTALDUE._serialized_start=245
  _AMOUNTTOTALDUE._serialized_end=529
# @@protoc_insertion_point(module_scope)
