// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: co2Monitoring.proto

package co2MonitoringService;

public final class co2MonitoringServiceImpl {
  private co2MonitoringServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_co2MonitoringService_DeviceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_co2MonitoringService_DeviceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_co2MonitoringService_DeviceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_co2MonitoringService_DeviceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_co2MonitoringService_Co2Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_co2MonitoringService_Co2Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_co2MonitoringService_Co2Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_co2MonitoringService_Co2Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023co2Monitoring.proto\022\024co2MonitoringServ" +
      "ice\"\035\n\rDeviceRequest\022\014\n\004text\030\001 \001(\t\"\037\n\016De" +
      "viceResponse\022\r\n\005value\030\001 \001(\t\",\n\nCo2Reques" +
      "t\022\016\n\006carbon\030\001 \001(\002\022\016\n\006oxygen\030\002 \001(\002\"\035\n\013Co2" +
      "Response\022\016\n\006result\030\001 \001(\t2\326\001\n\024co2Monitori" +
      "ngService\022d\n\025monitoringDeviceOnOff\022#.co2" +
      "MonitoringService.DeviceRequest\032$.co2Mon" +
      "itoringService.DeviceResponse\"\000\022X\n\013co2Em" +
      "ission\022 .co2MonitoringService.Co2Request" +
      "\032!.co2MonitoringService.Co2Response\"\000(\0010" +
      "\001B2\n\024co2MonitoringServiceB\030co2Monitoring" +
      "ServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_co2MonitoringService_DeviceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_co2MonitoringService_DeviceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_co2MonitoringService_DeviceRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_co2MonitoringService_DeviceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_co2MonitoringService_DeviceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_co2MonitoringService_DeviceResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_co2MonitoringService_Co2Request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_co2MonitoringService_Co2Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_co2MonitoringService_Co2Request_descriptor,
        new java.lang.String[] { "Carbon", "Oxygen", });
    internal_static_co2MonitoringService_Co2Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_co2MonitoringService_Co2Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_co2MonitoringService_Co2Response_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
