// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: co2Monitoring.proto

package co2MonitoringService;

public final class Co2MonitoringServiceImpl {
  private Co2MonitoringServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_co2MonitoringService_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_co2MonitoringService_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_co2MonitoringService_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_co2MonitoringService_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_co2MonitoringService_DeviceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_co2MonitoringService_DeviceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_co2MonitoringService_DeviceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_co2MonitoringService_DeviceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_co2MonitoringService_Co2Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_co2MonitoringService_Co2Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_co2MonitoringService_Co2Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_co2MonitoringService_Co2Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023co2Monitoring.proto\022\024co2MonitoringServ" +
      "ice\"\035\n\014PowerRequest\022\r\n\005power\030\001 \001(\010\"\036\n\rPo" +
      "werResponse\022\r\n\005power\030\001 \001(\010\"\035\n\rDeviceRequ" +
      "est\022\014\n\004text\030\001 \001(\t\"\037\n\016DeviceResponse\022\r\n\005v" +
      "alue\030\001 \001(\t\",\n\nCo2Request\022\016\n\006carbon\030\001 \001(\002" +
      "\022\016\n\006oxygen\030\002 \001(\002\"\035\n\013Co2Response\022\016\n\006resul" +
      "t\030\001 \001(\t2\260\002\n\024Co2MonitoringService\022X\n\013powe" +
      "rSwitch\022\".co2MonitoringService.PowerRequ" +
      "est\032#.co2MonitoringService.PowerResponse" +
      "\"\000\022d\n\025monitoringDeviceOnOff\022#.co2Monitor" +
      "ingService.DeviceRequest\032$.co2Monitoring" +
      "Service.DeviceResponse\"\000\022X\n\013co2Emission\022" +
      " .co2MonitoringService.Co2Request\032!.co2M" +
      "onitoringService.Co2Response\"\000(\0010\001B2\n\024co" +
      "2MonitoringServiceB\030Co2MonitoringService" +
      "ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_co2MonitoringService_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_co2MonitoringService_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_co2MonitoringService_PowerRequest_descriptor,
        new java.lang.String[] { "Power", });
    internal_static_co2MonitoringService_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_co2MonitoringService_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_co2MonitoringService_PowerResponse_descriptor,
        new java.lang.String[] { "Power", });
    internal_static_co2MonitoringService_DeviceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_co2MonitoringService_DeviceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_co2MonitoringService_DeviceRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_co2MonitoringService_DeviceResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_co2MonitoringService_DeviceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_co2MonitoringService_DeviceResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_co2MonitoringService_Co2Request_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_co2MonitoringService_Co2Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_co2MonitoringService_Co2Request_descriptor,
        new java.lang.String[] { "Carbon", "Oxygen", });
    internal_static_co2MonitoringService_Co2Response_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_co2MonitoringService_Co2Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_co2MonitoringService_Co2Response_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
