// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: co2Monitoring.proto

package co2MonitoringService;

public interface Co2RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:co2MonitoringService.Co2Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float carbon = 1;</code>
   */
  float getCarbon();

  /**
   * <code>float oxygen = 2;</code>
   */
  float getOxygen();
}
