// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: co2Monitoring.proto

package co2MonitoringService;

public interface DeviceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:co2MonitoringService.DeviceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
