// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: co2Monitoring.proto

package co2MonitoringService;

public interface PowerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:co2MonitoringService.PowerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool power = 1;</code>
   */
  boolean getPower();
}
